// <auto-generated />
namespace Inventory.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SplitOwnerNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SplitOwnerNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201702280255215_Split Owner Names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
